apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: dev
  namespace: argocd
spec:
  description: Developerment environment
  sourceRepos:
    - '*'

  destinations:
    - server: https://kubernetes.default.svc
      namespace: 'dev'
