apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-emoji-voto
spec:
  project: dev
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  source:
    repoURL: https://github.com/BuoyantIO/emojivoto.git
    targetRevision: HEAD
    path: kustomize/deployment
    kustomize: {}
